;; M5 (ADR-2607100100): generate the static kotoba-ui/liquid-glass-ui CSS
;; to public/vendor/. Same shape as murakumo-studio's
;; scripts/gen_kotoba_ui_css.clj (`bb ui-css`) — Tier A/B CSS is pure
;; functions over EDN rule data (kotoba-lang/css), no build step, run
;; with plain babashka. This app is always-dark (a real-time 3D viewport
;; doesn't have a light-mode use case), so Tier A emits dark tokens
;; directly on :root rather than gating on prefers-color-scheme.
(require '[clojure.java.io :as io]
         '[liquid-glass.tokens :as t]
         '[liquid-glass.style :as s])

(def app-css
  "/* --- kami-app-amenominaka shell --- */
html{min-height:100%}
body{margin:0;min-height:100vh;color:#eef1f6;
  font-family:-apple-system,'Hiragino Sans',sans-serif;font-size:14px;line-height:1.5;
  background:linear-gradient(160deg,#0b0d14 0%,#11131d 100%);
  background-attachment:fixed;overscroll-behavior:none;}
.am-shell{display:flex;flex-direction:column;height:100vh}
.am-body{display:flex;flex:1;min-height:0}
.am-sidebar{display:flex;flex-direction:column;width:260px;overflow-y:auto}
.am-env-panel{padding:16px;display:flex;flex-direction:column;gap:6px}
.am-env-panel h3{margin:0 0 8px}
.am-env-panel label{font-size:12px;opacity:.7;margin-top:10px}
.am-export-row{margin-top:16px;display:flex;flex-direction:column;gap:8px}
.am-timeline-panel{padding:16px;display:flex;flex-direction:column;gap:8px}
.am-timeline-panel h3{margin:0 0 4px}
.am-timeline-info{font-size:12px;opacity:.7}
.am-timeline-panel input[type=range]{width:100%}
.am-timeline-row{display:flex;flex-direction:column;gap:8px;margin-top:4px}
#viewport{flex:1;display:block;cursor:grab;width:100%;height:100%}
.liquid-glass__menu-select select option{color:#1c1c1e}
")

(def css
  (str "/* generated by scripts/gen_kotoba_ui_css.clj (`bb ui-css`) — do not hand-edit\n"
       "   tokens/style = kotoba-lang/liquid-glass-ui (via kotoba-lang/css EDN rules) */\n"
       (t/css-variables (t/resolve-dark-tokens nil))
       "\n"
       (s/component-css)
       "\n"
       app-css))

(let [out "public/vendor/kotoba-ui.css"]
  (io/make-parents out)
  (spit out css)
  (println "✓" out (str "(" (count css) " bytes)")))
